[package]
name = "api-service"
version = "1.0.0"
edition = "2021"

[dependencies]
tonic = "0.12.3"
prost = "0.13.4"
tokio-stream = "0.1.17"
anyhow = "1.0.95"
async-trait = "0.1.83"
axum = { version = "0.8.1", features = ["tower-log"] }
axum-extra = { version = "0.10.0", features = ["cookie"] }
backtrace = "0.3.74"
clap = { version = "4.5.23", features = ["derive", "env"] }
dotenvy = "0.15.6"
http-body = "1.0.1"
jsonwebtoken = "9.3.0"
lazy_static = "1.5.0"
metrics = "0.24.1"
rust-argon2 = "2.1.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
thiserror = "2.0.9"
tokio = { version = "1.42.0", features = ["full"] }
tower = { version = "0.5.2", features = ["timeout", "buffer", "limit"] }
tower-http = { version = "0.6.2", features = ["trace", "cors"] }
tracing = "0.1.41"
tracing-appender = "0.2.2"
tracing-subscriber = "0.3.19"
uuid = { version = "1.11.0", features = ["v4", "serde"] }
validator = { version = "0.20.0", features = ["derive"] }
reqwest = { version = "0.12.12", features = ["json", "multipart", "stream"] }
# openai-api-rs = "4.0.8"
async-openai = "0.27.2"
sqlx = { version = "0.8.2", features = [
    "runtime-tokio",
    "postgres",
    "time",
    "uuid",
] }
rutils = { path = "../rutils" } # 保留这一行，删除下面的重复声明

[build-dependencies]
tonic-build = "0.12.3"
